// loom-angular-app/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
// import { isSupported, setup } from "@loomhq/loom-sdk";
// import { oembed } from "@loomhq/loom-embed";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'HMS-LOOM-App';
  // API_KEY = "454de8ec-4232-415a-9199-cd95cfbdfb85";
  // BUTTON_ID = "loom-sdk-button";

  // insertEmbedPlayer(html: string) {
  //   const target = document.getElementById("target");
  //   if (target) { target.innerHTML = html; }
  // }
  // async init() {
  //   const { supported, error } = await isSupported();
  //   if (!supported) { console.log(`Error setting up Loom: ${error}`); return; } else { console.log("all good") }
  // }

  async ngOnInit() {
    // this.init();
    // const root = document.getElementById("app");
    // if (!root) { return; }
    // root.innerHTML = `<button id="${this.BUTTON_ID}">Record</button>`;
    // const button = document.getElementById(this.BUTTON_ID);
    // if (!button) { return; }
    // const { configureButton } = await setup({ apiKey: "454de8ec-4232-415a-9199-cd95cfbdfb85" });
    // const sdkButton = configureButton({ element: button });
    // sdkButton.on("insert-click",
    //   async video => {
    //     const { html } = await oembed(video.sharedUrl, { width: 400 });
    //     this.setData(video.sharedUrl);
    //     this.insertEmbedPlayer(html);
    //   });
  }

  setData(url: string) {
    console.log(url);
  }

}

// loom-react-app/src/App.js
import logo from './logo.svg';
import './App.css';

// function App() {
//   return (
//     <div className="App">
//       <header className="App-header">
//         <img src={logo} className="App-logo" alt="logo" />
//         <p>
//           Edit <code>src/App.js</code> and save to reload.
//         </p>
//         <a
//           className="App-link"
//           href="https://reactjs.org"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Learn React
//         </a>
//       </header>
//     </div>
//   );
// }

// export default App;

import { setup, isSupported } from "@loomhq/loom-sdk";
import { oembed } from "@loomhq/loom-embed";
import { useEffect, useState } from "react";

const API_KEY = "api-key-obtained-from-developer-portal";
const BUTTON_ID = "loom-sdk-button";

export default function App() {
  const [videoHTML, setVideoHTML] = useState("");

  useEffect(() => {
    async function setupLoom() {
      const { supported, error } = await isSupported();

      if (!supported) {
        console.warn(`Error setting up Loom: ${error}`);
        return;
      }

      const buttonRec = document.getElementById(BUTTON_ID);

      if (!buttonRec) {
        return;
      }

      const { configureButton } = await setup({
        apiKey: ""
      });

      const sdkButton = configureButton({ element: buttonRec });

      sdkButton.on("insert-click", async video => {
        const { html } = await oembed(video.sharedUrl, { width: 400 });
        setVideoHTML(html);
      });
    }

    setupLoom();
  }, []);

  return (
    <>
      <button id={BUTTON_ID}>Record</button>
      <div dangerouslySetInnerHTML={{ __html: videoHTML }}></div>
    </>
  );
}
